### ISSUE TITLE
Ability to read task ID from functions decorated with `celery::task`

### ISSUE THREAD

**Issue by peter-subscale** [rusty-celery/rusty-celery#153]
**Is your feature request related to a problem? Please describe.**

There is no way to get the current task ID when running a task.  This could be useful in tracing execution contexts etc... 

**Describe the solution you'd like**

Ability to inject the ID as a command argument when using `celery::task` a bit like bind is used.

**Describe alternatives you've considered**

I'm not sure it's possible without re-implementing a lot of the plumbing

**Additional context**

N/A

**Comment by epwalsh** [comment]
Hi @peter-subscale, there is actually a way to do this right now. When you define your task, use the `bind = true` option. Check out this example: https://github.com/rusty-celery/rusty-celery/blob/master/examples/celery_app.rs#L36

This gives the task function access to `&task`, which implements the [`Task` trait](https://docs.rs/celery/0.3.1/celery/task/trait.Task.html). Then you can call `task.request().id` to get the task ID.

**Comment by peter-subscale** [comment]
Ah, no worries. I wasn't sure that it was possible.  I'll close this issue off.
