### ISSUE TITLE
How can the provider get the result when the consumer finish the task?

### ISSUE THREAD

**Issue by dancespiele** [rusty-celery/rusty-celery#202]
Hello, first, great job, this looks really promising. I'm wondering if it possible that the `provider` can get the result once that the `consumer` finish the task. In case that it is, could you provide me an example please? Thanks in advance!

**Comment by epwalsh** [comment]
Hi @dancespiele, thanks for the kind words 😄 

This would be provided by a [Backend](https://github.com/rusty-celery/rusty-celery#backends). Unfortunately we haven't implemented that feature yet.

An alternative would be to use a [task callback](https://rusty-celery.github.io/guide/defining-tasks.html#callbacks) that stores the result of the task in a database with task ID as the primary key. Then the producer could poll the database for the result. That's actually pretty much exactly how a Backend works anyway.

**Comment by dancespiele** [comment]
Thanks a lot for your answer @epwalsh. I think I have an idea how can do according what you explained to me. I can save the result with the callback in the database and when I send the task it responses me with the task ID, then I can retrieve from the database the result doing a loop that once that I get it the loop is finish or in case that 3 times the data was not available. If there is better way to process please let me know. 
I'm wondering how can deserialize the data that come with [&T::Returns](https://docs.rs/celery/0.3.1/celery/task/trait.Task.html#associatedtype.Returns)

**Comment by epwalsh** [comment]
Yes, that's the idea. You could use [`serde`](https://serde.rs/) to serialize the `T::Result` within the callback and to deserialize it when the producer fetches it from the database.

**Comment by dancespiele** [comment]
sorry that I bother you @epwalsh, I tried to serialize like this

```rust
async fn print_response_consumer<T:Task>(_task: &T, ret: &T::Returns) {
    let text: String = serde_json::to_string(ret).unwrap(); 
    println!("response consumer: {:?}", text);
}
```

However I get this error:

```
the trait bound `<T as celery::task::Task>::Returns: _::_serde::Serialize` is not satisfied
the trait `_::_serde::Serialize` is not implemented for `<T as celery::task::Task>::Returns`
```

**Comment by epwalsh** [comment]
You could do something like this:

```rust
#[derive(Debug, Serialize, Deserialize)]
struct RetObject {
    a: i32,
}

async fn save_to_backend(_task: &task_with_callbacks, ret: &RetObject) {
    let serialized = serde_json::to_string(ret).unwrap();
    println!("Saving {} to database", &serialized[..]);
}

// Demonstrates using callbacks with a task.
#[celery::task(on_success = save_to_backend)]
fn task_with_callbacks() -> TaskResult<RetObject> {
    Ok(RetObject { a: 0 })
}
```

**Comment by dancespiele** [comment]
I resolved like this in this case:

```rust
async fn print_response_consumer<T:Task>(_task: &T, ret: &T::Returns) 
    where T::Returns: ToString {
    let text = ret.to_string(); 
    println!("response consumer: {:?}", text);
}
```

**Comment by dancespiele** [comment]
@epwalsh I close this ticket. In the end I created theses examples:

**Celery provider**: https://github.com/dancespiele/celery_provider
**Celery consumer**: https://github.com/dancespiele/celery_consumer

Thanks for your help! :rocket:

**Comment by epwalsh** [comment]
Those look great!
