### ISSUE TITLE
How to unit test a task?

### ISSUE THREAD

**Issue by Fedalto** [rusty-celery/rusty-celery#234]
Say we have the task:
```rust
use celery::prelude::*;

#[celery::task]
fn add(x: i32, y: i32) -> TaskResult<i32> {
    Ok(x + y)
}
```
Is there a way to unit test the `add` task?
I'm looking for something like:
```rust
#[test]
fn test_add_task() {
    let celery_app = celery::app!(...);
    let result = ??? // Somehow execute add(2, 3) and retrieve the result
    assert_eq!(result, Ok(5));
```

**Comment by epwalsh** [comment]
Hey @Fedalto, sorry for the late response!

You could do `let result = add::_run(1, 2).unwrap()`.

**Comment by epwalsh** [comment]
Keep in mind that if your task is async, the `_run` function will also be async. This comes from here: https://github.com/rusty-celery/rusty-celery/blob/37198a0a7f71174bf73d52ff07cde7d49b36bdbd/celery-codegen/src/task.rs#L574-L592

**Comment by Fedalto** [comment]
This should work. Thanks

**Comment by epwalsh** [comment]
Great!

**Comment by rbozan** [comment]
It's great that there is support for this, but could this be documented somewhere please?
