### ISSUE TITLE
Example for sharing data between tasks (for example a database connection pool)

### ISSUE THREAD

**Issue by the-bass** [rusty-celery/rusty-celery#265]
**Is your feature request related to a problem? Please describe.**
When spawning a lot of tasks at once it's not feasible anymore to open a new database connection for every task.

**Describe the solution you'd like**
I'd like to build a database connection pool once, just before starting a celery consumer and then pass this pool to each task the consumer fetches. Is that already possible somehow? And, if so, could this be showcased in an example?

**Describe alternatives you've considered**

**Additional context**

In any case, thanks a lot for your work so far!

**Comment by epwalsh** [comment]
Hey @the-bass! Have you tried using [`once_cell`](https://docs.rs/once_cell/1.8.0/once_cell/index.html) to create a global connection pool? Or does that not work for some reason?

**Comment by the-bass** [comment]
I hadn't heard of `once_cell` before, but turns out that it indeed works perfectly for my use case. Thanks a lot for the hint, @epwalsh!

**Comment by epwalsh** [comment]
Glad to hear it!
