### ISSUE TITLE
0.4.0-rcN version suffixes are not SemVer-compatible

### ISSUE THREAD

**Issue by PiDelport** [rusty-celery/rusty-celery#275]
**Describe the bug**

The current 0.4.0-rcN pre-release version numbers are missing a dot separator between the **rc** and **N**, causing them to be sorted in ASCII order rather than numerically. ([SemVer spec item](https://semver.org/#spec-item-11))

**To Reproduce**

This affects release 0.4.0-rc10, in particular. <https://crates.io/crates/celery/versions?sort=semver> shows the issue, with:

- 0.4.0-**rc1** < 0.4.0-**rc10** < 0.4.0-**rc2**
- 0.4.0-**rc8** still listed as the latest version, currently

**Expected behavior**

Releasing the next RC as **0.4.0-rc.11** would be conventional, but this has lower precedence than the existing 0.4.0 RCs.

As a workaround for 0.4.0, the next RC could be versioned as **0.4.0-rcnext.11** or similar, to compare higher than the existing RCs.

**Comment by epwalsh** [comment]
Well that's annoying! But good to know... Thanks for looking into that. Fixed by https://github.com/rusty-celery/rusty-celery/commit/a7ddb20dde013f0985e04059602c840b697a14ea.
