### ISSUE TITLE
Add app autoregistration and default name to task definition macro

### ISSUE THREAD

**Issue by tjhall13** [rusty-celery/rusty-celery#28]
Add a required(?) positional argument to the task macro that is the app the task needs to be registered on. Also make the name of the task inferred from the function name if not explicitly defined like how python celery does.

**Comment by tjhall13** [comment]
Looked into the app autoregistration idea and it is more complicated than I originally thought. There are problems with defining the app before the task and exactly when the app would register the task. I can come back to that later

**Comment by epwalsh** [comment]
Hmm yea and in most cases I think people will define their tasks at the module level but only instantiate the app in their `main` function. Maybe we could have a global object that keeps track of tasks. When someone defines a task through the macro, the macro could add code that will add to the global object. Then when the celery app is instantiated it registers all the tasks from this global registry.
