### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by AzHicham** [rusty-celery/rusty-celery#342]
Hello, 

First of all, thank you for this project. It's hard to find in Rust ecosystem a working equivalent of celery/dramatiq. 

I would like to know if the project is not maintained anymore and if you are planning to release a new version soon ? 

Thanks

**Comment by epwalsh** [comment]
Hi @AzHicham, the project is "sort of" maintained. I've been looking for other maintainers to step on for a while because I don't have the time anymore, but so far I've had no luck. I still try to respond to PRs and issues when I can. I can certainly run a new release.

**Comment by epwalsh** [comment]
v0.4.0 is out now: https://crates.io/crates/celery
