### ISSUE TITLE
BrokerBuilder is not Send

### ISSUE THREAD

**Issue by Miezhiko** [rusty-celery/rusty-celery#354]
```
note: future is not `Send` as this value is used across an await
   --> ~/.cargo/git/checkouts/rusty-celery-cac4a481213716fc/6a71f33/src/broker/mod.rs:162:55
    |
162 |         match broker_builder.build(connection_timeout).await {
    |               --------------                          ^^^^^^ await occurs here, with `broker_builder` maybe used later
    |               |
    |               has type `&dyn BrokerBuilder` which is not `Send`
...
179 |         };
    |          - `broker_builder` is later dropped here
```

**Comment by epwalsh** [comment]
Hey @Miezhiko could you post some code to reproduce this?

**Comment by Miezhiko** [comment]
> Hey @Miezhiko could you post some code to reproduce this?

it's something with this https://github.com/Miezhiko/Amadeus/blob/mawa/Amadeus/src/salieri/mod.rs#L25-L28 (Arc Mutex Lazy Static Option)

most likely related to this change: https://github.com/rusty-celery/rusty-celery/commit/25168a5e2a132ef87d7c75bebed4ac58de147e32

**Comment by epwalsh** [comment]
Hmm ok.. maybe it's enough to require `BrokerBuilder` be `Send + Sync`? Can you try on this branch: https://github.com/rusty-celery/rusty-celery/pull/355?

**Comment by Miezhiko** [comment]
@epwalsh yes, will try soon

**Comment by Miezhiko** [comment]
@epwalsh tested, works!

**Comment by epwalsh** [comment]
Okay, great! That was surprisingly easy... 🙂

I'll merge that and then cut a patch release
