### ISSUE TITLE
WARN celery::broker::redis:Setting heartbeat on redis broker has no effect on anything

### ISSUE THREAD

**Issue by jiangxiaoqiang** [rusty-celery/rusty-celery#364]
**Describe the bug**
when I run the celery, shows warning: WARN celery::broker::redis:Setting heartbeat on redis broker has no effect on anything

is it possible to make the warning disappear?

**Comment by epwalsh** [comment]
Hey @jiangxiaoqiang, I've opened to #365 to address this. Can you tell me if that works for you?

**Comment by jiangxiaoqiang** [comment]
I can't verify right now, I will try to verify this issue on the next release version. I have read the file change seems  that what I want without warning if not nessasary. @epwalsh
