### ISSUE TITLE
Implement celery beat

### ISSUE THREAD

**Issue by epwalsh** [rusty-celery/rusty-celery#55]

**Comment by crash-g** [comment]
Hi @epwalsh, I would be happy to give this a try, although I'm not an expert on the subject

**Comment by epwalsh** [comment]
@crash-g that would be much appreciated!

**Comment by crash-g** [comment]
Great, is there a channel we can use to coordinate a little more easily (Matrix, Discord, Slack or similar)?

**Comment by epwalsh** [comment]
Sure, are you okay with Discord? That seems to be popular with Rust developers
