### ISSUE TITLE
Implement Redis broker

### ISSUE THREAD

**Issue by epwalsh** [rusty-celery/rusty-celery#6]

**Comment by epwalsh** [comment]
Depends on async pub sub: https://github.com/mitsuhiko/redis-rs/pull/287

This is now merged but not released

**Comment by Abhishek8394** [comment]
I would like to take a stab at this. I can try mimicking the way amqp broker is implemented.

**Comment by epwalsh** [comment]
@Abhishek8394 that would be much appreciated!

**Comment by Abhishek8394** [comment]
@epwalsh Does this look like the correct way to do it? 
- Create a redis list where list key is queue name.
- Each queue also gets a corresponding `*-processing` list. 
- On `consume(queue)` it expects a future stream.
    - loop on `*-processing` queue
- On `ack`
    - Remove item from `*-processing` queue
- On `retry`
    - Push item back in `*-processing` queue?
- The role of `*_channel` is not clear to me, it seems like an AMQP thing so far. The [MultiplexedConnection][1] would do the role of both? Maybe create dummy channel that wraps around multiplexed connection?

#### Broker
```rust
struct RedisBroker{
    connection: MultiplexedConnection, 
    consume_channel: Something?,
    produce_channel: Something?,
    queues: HashSet<String>, // Use queue names as redis list key
}
```

[1]: https://docs.rs/redis/0.16.0/redis/aio/struct.MultiplexedConnection.html

**Comment by epwalsh** [comment]
Hey @Abhishek8394, I'm really not sure the best way to do it, but I think the best source to look at would be the Python equivalent from the `kombu` package: https://github.com/celery/kombu/blob/master/kombu/transport/redis.py

**Comment by Abhishek8394** [comment]
So it seems kombu uses `n` lists for `n` queues and a single processing queue. They also use a hashmap to keep track of "processing" jobs. I think we can do that either with `redis::Pipeline` or `brpoplpush`. However an issue I ran into is that the redis library expects a mutable connection object whereas the `Broker` trait provides immutable `self` refs. Two potential solutions below.

1. Use `RefCell` to wrap connections. I tried this but the `Send` trait is not satisfied for something like `&mut *conn.borrow_mut()`. So not sure how to proceed further with this.
2. Use unsafe code, haven't tried this but there should be a better way to do this.

[code here](https://github.com/Abhishek8394/rusty-celery/blob/redis-broker/src/broker/redis.rs#L193)

**Comment by epwalsh** [comment]
Hey @Abhishek8394, I'd like to stick with the "interior mutability" pattern that the `Broker` currently has, i.e. keep the `self` refs immutable. So instead of `RefCell` you could use `Mutex`. See https://doc.rust-lang.org/book/ch16-03-shared-state.html#similarities-between-refcelltrct-and-mutextarct, for example.

**Comment by Abhishek8394** [comment]
I would need to also implement serialization of message headers. I want to keep its parsing decoupled from message parsing. I was wondering if we could encode the entire payload like a HTTP request with binary payload. This could also lend itself to reusability for other non-AMQP backends. Let me know if this sounds like a good idea.

**Comment by Abhishek8394** [comment]
Hey @epwalsh I have a working mechanism to push/pull messages to/from redis! I still need to implement things like ack, retry and close. But I wanted you to take a look at the implementation so far. It can be ran from the example celery app too. 

Issues / concerns:

- The main consume loop only seems to be able to pick up tasks that were produced before but not after its launch. I cannot seem to find the correct place to invoke the waker. Or maybe it has nothing to do with waker but the objects returned from Stream's next method.

- Is it correct that we cannot do async work inside the `DeliveryStream` ? I currently clone the `redis::Client` for each channel because MultiplexeConnection works for async calls only. Not sure if cloning  `redis::Client` creates a new connection each time.
