### ISSUE TITLE
Populate origin field of MessageHeaders

### ISSUE THREAD

**Issue by epwalsh** [rusty-celery/rusty-celery#66]
This comes from https://docs.celeryproject.org/en/latest/internals/reference/celery.utils.nodenames.html#celery-utils-nodenames

**Comment by RestitutorOrbis** [comment]
Are there test cases for this issue? @epwalsh

**Comment by epwalsh** [comment]
@RestitutorOrbis not at the moment, but in the Python implementation it looks like this comes directly from here: https://docs.celeryproject.org/en/latest/internals/reference/celery.utils.nodenames.html#celery.utils.nodenames.anon_nodename

**Comment by RestitutorOrbis** [comment]
@epwalsh Cool, thanks!

**Comment by RestitutorOrbis** [comment]
@epwalsh Which files should I take a look at on the Rust side of things?

**Comment by epwalsh** [comment]
I think it would make sense to handle this within the `MessageBuilder` struct in the protocol module. I don't think we really need to expose a method to set this, but we should just populate this field within [`MessageBuilder::new`](https://github.com/rusty-celery/rusty-celery/blob/65b4a1c8f596a8a80fbb6fef6df617c91ac34ffe/src/protocol/mod.rs#L26) according to how it's done in Python. Let me know if you have any other questions!

**Comment by RestitutorOrbis** [comment]
Would it be alright to add this to make it easier to get the hostname? 
https://docs.rs/hostname/0.3.0/hostname/

**Comment by epwalsh** [comment]
@RestitutorOrbis sure!

**Comment by RestitutorOrbis** [comment]
@epwalsh Do you happen to have any idea on how to resolve this error? It seems to be an issue with the bytes dependency in tokio-rs. I didn't see it on CI so I suspect it's a problem with my machine.
```
Downloaded memchr v2.3.2
  Downloaded backtrace v0.3.44
  Downloaded serde_json v1.0.48
   Compiling proc-macro2 v1.0.8
   Compiling unicode-xid v0.2.0
   Compiling semver-parser v0.7.0
   Compiling libc v0.2.66
   Compiling syn v1.0.14
   Compiling getrandom v0.1.14
   Compiling ucd-trie v0.1.2
   Compiling cfg-if v0.1.10
   Compiling arrayvec v0.4.12
   Compiling ryu v1.0.2
   Compiling maplit v1.0.2
   Compiling ppv-lite86 v0.2.6
   Compiling core-foundation-sys v0.6.2
   Compiling memchr v2.3.2
   Compiling version_check v0.1.5
   Compiling serde v1.0.104
   Compiling nodrop v0.1.14
   Compiling log v0.4.8
   Compiling static_assertions v0.3.4
   Compiling matches v0.1.8
   Compiling itoa v0.4.5
   Compiling same-file v1.0.6
   Compiling smallvec v1.2.0
   Compiling remove_dir_all v0.5.2
   Compiling cookie-factory v0.3.1
   Compiling native-tls v0.2.3
   Compiling quick-error v1.2.3
   Compiling slab v0.4.2
   Compiling proc-macro-nested v0.1.3
   Compiling autocfg v1.0.0
   Compiling percent-encoding v2.1.0
   Compiling cc v1.0.50
   Compiling lazy_static v1.4.0
   Compiling proc-macro2 v0.4.30
   Compiling autocfg v0.1.7
   Compiling unicode-xid v0.1.0
   Compiling futures-sink v0.3.4
   Compiling futures-core v0.3.4
   Compiling pin-utils v0.1.0-alpha.4
   Compiling failure_derive v0.1.6
   Compiling scopeguard v1.0.0
   Compiling futures-task v0.3.4
   Compiling syn v0.15.44
   Compiling futures-io v0.3.4
   Compiling arc-swap v0.4.4
   Compiling rustc-demangle v0.1.16
   Compiling regex-syntax v0.6.14
   Compiling pin-project-lite v0.1.4
   Compiling bytes v0.5.4
error[E0658]: naming constants with `_` is unstable
   --> /Users/javednissar/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.5.4/src/bytes.rs:911:1
    |
911 | const _: [(); 0 - mem::align_of::<Shared>() % 2] = []; // Assert that the alignment of `Shared` is divisible by 2.
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/54912

   Compiling fnv v1.0.6
   Compiling termcolor v1.1.0
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `bytes`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by epwalsh** [comment]
Hey @RestitutorOrbis, what version of `rustc` are you using?

**Comment by RestitutorOrbis** [comment]
rustc 1.36.0 (a53f9df32 2019-07-03)

**Comment by epwalsh** [comment]
I think it will work if you update your toolchain to a new version. Try running `rustup update` and then compiling again

**Comment by RestitutorOrbis** [comment]
Thanks @epwalsh! It worked! It looks like there's still some issues with CI run that I'll hopefully get fixed over the weekend.
