### ISSUE TITLE
Add routing options to protocol

### ISSUE THREAD

**Issue by epwalsh** [rusty-celery/rusty-celery#80]
See https://docs.celeryproject.org/en/latest/userguide/calling.html#routing-options

**Comment by alekhrycaiko** [comment]
Hey epwalsh I"m getting familiar/w the repo (and looking where to help out) and was wondering whether this has been completed yet. Afaik, the `reply_to` protocol seems completed, and the sending of tasks to queues appears completed [here](https://github.com/rusty-celery/rusty-celery/blob/26c8c2ec7e4a3106c83c0329cf23f9e4634fc080/src/app/mod.rs#L331). Is there anything else missing in terms of routing that I've missed?

**Comment by epwalsh** [comment]
Hey @alekhrycaiko, I'm not entirely sure what I had in mind when I first opened this a while ago 😬. But it looks like we are still missing some routing features, like priority and exchange type. See https://docs.celeryproject.org/en/latest/userguide/routing.html#special-routing-options, for example.

I'd say these are pretty low priority though.

**Comment by epwalsh** [comment]
Ah, this is probably covered by https://github.com/rusty-celery/rusty-celery/issues/85.
