### ISSUE TITLE
Complete the `MessageBuilder` struct

### ISSUE THREAD

**Issue by epwalsh** [rusty-celery/rusty-celery#99]
`celery::protocol::MessageBuilder` should have methods to set all fields within `MessageProperties` and `MessageHeaders`.

**Comment by s00kee** [comment]
Hi, I would like to take a shot at this (disclaimer: I'm very new to Rust). Thanks.

**Comment by epwalsh** [comment]
That would be great @s00kee ! Let me know if you get stuck

**Comment by s00kee** [comment]
I just took a look at it. Just to make sure I got it right, I am to write a setter method for each field within 
- `MessageProperties` found [here](https://docs.rs/celery/0.2.5/celery/protocol/struct.MessageProperties.html)
- `MessageHeaders` found [here](https://docs.rs/celery/0.2.5/celery/protocol/struct.MessageHeaders.html)

I'm thinking of adding these setters to the end of `impl<T> MessageBuilder<T>` in file `src/protocol/mod.rs` with each looking something like this
```Rust
pub fn set_correlation_id(&mut self, id: String) {
 self.message.properties.correlation_id = id.clone();
}
```
Let me know what you think. Thanks :smiley:

**Comment by epwalsh** [comment]
Hi @s00kee, yes that's correct. Although by convention the name of the setter would just be `correlation_id` instead of `set_correlation_id`. I think the rational behind that is that with a "Builder" struct every method is assumed to be a "setter" method, and so adding `set_` to a method name is somewhat redundant.

**Comment by s00kee** [comment]
Hi @epwalsh, for something with `Option<T>` as a function argument such as [`shadow`](https://docs.rs/celery/0.2.5/celery/protocol/struct.MessageHeaders.html#structfield.shadow), I'm not sure whether to go with 
```Rust
    pub fn shadow(&mut self, shadow: Option<String>) {
        self.message.headers.shadow = shadow;
    }
```
or 
```Rust
    pub fn shadow(&mut self, shadow: String) {
        self.message.headers.shadow = Some(shadow);
    }
```
What do you think?

**Comment by epwalsh** [comment]
I think since the default is already `None` it makes sense to have it be `shadow: String` instead of `shadow: Option<String>`
